version: '2'
services:
  home-notifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-notifier
    restart: unless-stopped
    network_mode: host
    environment:
       SPEAKERS: 'Basement speaker'
       NGROK_SLUG: 'imr-messenger-8334'
